export const EQUIPMENT_TYPES = [
  "Inspection Equipment",
  "Cleaning Equipment",
  "Assembly Equipment",
  "Marking Equipment",
  "SMT Equipment",
  "Thermal Equipment",
  "Printing Equipment",
  "Rework Equipment",
  "Quality Control Equipment",
  "Soldering Equipment",
  "Testing Equipment",
]

export const EQUIPMENT_STATUSES = ["Operational", "Maintenance", "Offline"]

export const EQUIPMENT_TYPE_ICONS: Record<string, string> = {
  "inspection equipment": "eye",
  "cleaning equipment": "tool",
  "assembly equipment": "settings",
  "marking equipment": "tool",
  "smt equipment": "cpu",
  "thermal equipment": "gauge",
  "printing equipment": "printer",
  "rework equipment": "wrench",
  "quality control equipment": "check-circle",
  "soldering equipment": "zap",
  "testing equipment": "hard-drive",
}

// Define STORAGE_KEYS locally since it's not exported from constants
export const STORAGE_KEYS = {
  STATIONS: "meritronics-stations",
  EQUIPMENT: "meritronics-equipment",
  SETTINGS: "meritronics-settings",
  USER_PREFERENCES: "meritronics-user-preferences",
}

// Mock Equipment Data
export const MOCK_EQUIPMENT = [
  {
    id: "eq-aoi-system-456",
    name: "Automated Optical Inspection System",
    status: "operational",
    type: "Inspection Equipment",
    serialNumber: "AOI-2345-2023",
    model: "AOI-3D-Pro",
    manufacturer: "TechEquip Inc.",
    purchaseDate: "15-06-2022",
    lastMaintenance: "15-03-2023",
    nextMaintenance: "15-06-2023",
    location: "Building A, Floor 1, Section 3",
    assignedStation: "AOI Station 1",
    notes: "High-precision 3D inspection system for PCB quality control.",
  },
  {
    id: "eq-chemical-wash-789",
    name: "Chemical Wash System",
    status: "maintenance",
    type: "Cleaning Equipment",
    serialNumber: "CWS-1234-2022",
    model: "ChemClean 5000",
    manufacturer: "CleanTech Solutions",
    purchaseDate: "20-05-2022",
    lastMaintenance: "10-02-2023",
    nextMaintenance: "10-05-2023",
    location: "Building A, Floor 1, Section 5",
    assignedStation: "Chemical Wash Station",
    notes: "Industrial-grade chemical cleaning system for PCB processing.",
  },
  {
    id: "eq-component-placement-101",
    name: "Component Placement System",
    status: "operational",
    type: "Assembly Equipment",
    serialNumber: "CPS-5678-2023",
    model: "HandPlace Pro",
    manufacturer: "AssemblyTech",
    purchaseDate: "10-07-2022",
    lastMaintenance: "20-04-2023",
    nextMaintenance: "20-07-2023",
    location: "Building B, Floor 2, Section 1",
    assignedStation: "Hand Placement Station 1",
    notes: "Precision manual component placement system with optical guidance.",
  },
  {
    id: "eq-laser-etching-202",
    name: "Laser Etching System",
    status: "operational",
    type: "Marking Equipment",
    serialNumber: "LES-9012-2022",
    model: "LaserMark X5",
    manufacturer: "PrecisionTools",
    purchaseDate: "05-08-2022",
    lastMaintenance: "05-03-2023",
    nextMaintenance: "05-06-2023",
    location: "Building B, Floor 2, Section 3",
    assignedStation: "Laser Etching Station 1",
    notes: "High-power laser etching system for PCB marking and serialization.",
  },
  {
    id: "eq-pick-place-303",
    name: "Pick and Place Machine",
    status: "operational",
    type: "SMT Equipment",
    serialNumber: "PPM-3456-2023",
    model: "SMT-Placer 8000",
    manufacturer: "SMTech",
    purchaseDate: "12-09-2022",
    lastMaintenance: "12-04-2023",
    nextMaintenance: "12-07-2023",
    location: "Building A, Floor 2, Section 2",
    assignedStation: "Pick and Place Station 1",
    notes: "High-speed automated component placement machine for SMT assembly.",
  },
  {
    id: "eq-pth-insertion-404",
    name: "Through-hole Insertion System",
    status: "offline",
    type: "Assembly Equipment",
    serialNumber: "TIS-7890-2022",
    model: "PTH-Insert 3000",
    manufacturer: "AssemblyTech",
    purchaseDate: "08-10-2022",
    lastMaintenance: "25-02-2023",
    nextMaintenance: "25-05-2023",
    location: "Building C, Floor 1, Section 1",
    assignedStation: "PTH Manual Load Station",
    notes: "Semi-automated through-hole component insertion system.",
  },
  {
    id: "eq-reflow-oven-505",
    name: "Reflow Oven",
    status: "operational",
    type: "Thermal Equipment",
    serialNumber: "RFO-2345-2022",
    model: "ThermalFlow Pro",
    manufacturer: "ThermalTech",
    purchaseDate: "15-11-2022",
    lastMaintenance: "18-03-2023",
    nextMaintenance: "18-06-2023",
    location: "Building A, Floor 2, Section 4",
    assignedStation: "Reflow Oven Station",
    notes: "10-zone reflow oven with precise temperature control for SMT assembly.",
  },
  {
    id: "eq-screen-printer-606",
    name: "Screen Printer",
    status: "operational",
    type: "Printing Equipment",
    serialNumber: "SPR-6789-2023",
    model: "PrintMaster 7000",
    manufacturer: "PrintTech Solutions",
    purchaseDate: "10-12-2022",
    lastMaintenance: "02-04-2023",
    nextMaintenance: "02-07-2023",
    location: "Building B, Floor 1, Section 2",
    assignedStation: "Screen Printing Station 1",
    notes: "High-precision solder paste screen printer with automatic alignment.",
  },
  {
    id: "eq-rework-station-707",
    name: "Rework Station",
    status: "operational",
    type: "Rework Equipment",
    serialNumber: "RWS-1234-2022",
    model: "ReworkPro X3",
    manufacturer: "RepairTech",
    purchaseDate: "05-01-2023",
    lastMaintenance: "08-03-2023",
    nextMaintenance: "08-06-2023",
    location: "Building C, Floor 1, Section 3",
    assignedStation: "Touch Up Station 1",
    notes: "Advanced rework station with hot air, soldering iron, and preheater.",
  },
  {
    id: "eq-inspection-system-808",
    name: "Inspection System",
    status: "operational",
    type: "Quality Control Equipment",
    serialNumber: "INS-5678-2023",
    model: "QualityView Pro",
    manufacturer: "QualityMachines",
    purchaseDate: "12-02-2023",
    lastMaintenance: "15-04-2023",
    nextMaintenance: "15-07-2023",
    location: "Building A, Floor 1, Section 1",
    assignedStation: "Visual Inspection Station 1",
    notes: "Visual inspection system with magnification and lighting controls.",
  },
  {
    id: "eq-pcb-washing-909",
    name: "PCB Washing System",
    status: "maintenance",
    type: "Cleaning Equipment",
    serialNumber: "PWS-9012-2022",
    model: "AquaClean 4000",
    manufacturer: "CleanTech Solutions",
    purchaseDate: "25-01-2023",
    lastMaintenance: "20-02-2023",
    nextMaintenance: "20-05-2023",
    location: "Building B, Floor 1, Section 4",
    assignedStation: "Wash Clean Station",
    notes: "Automated PCB washing system with multi-stage cleaning process.",
  },
  {
    id: "eq-wave-solder-010",
    name: "Wave Soldering Machine",
    status: "operational",
    type: "Soldering Equipment",
    serialNumber: "WSM-3456-2022",
    model: "WavePro 6000",
    manufacturer: "SolderMasters",
    purchaseDate: "08-02-2023",
    lastMaintenance: "10-03-2023",
    nextMaintenance: "10-06-2023",
    location: "Building C, Floor 2, Section 2",
    assignedStation: "Wave Soldering Station",
    notes: "Dual-wave soldering machine for through-hole component soldering.",
  },
  {
    id: "eq-xray-system-111",
    name: "X-Ray Inspection System",
    status: "operational",
    type: "Inspection Equipment",
    serialNumber: "XRS-7890-2023",
    model: "X-Vision 3D",
    manufacturer: "InspectionTech",
    purchaseDate: "01-03-2023",
    lastMaintenance: "05-04-2023",
    nextMaintenance: "05-07-2023",
    location: "Building A, Floor 2, Section 5",
    assignedStation: "X-Ray Inspection Station",
    notes: "Advanced X-ray inspection system for BGA and hidden solder joint inspection.",
  },
  {
    id: "eq-spare-aoi-212",
    name: "Spare AOI System",
    status: "operational",
    type: "Inspection Equipment",
    serialNumber: "AOI-8765-2022",
    model: "AOI-2D-Standard",
    manufacturer: "TechEquip Inc.",
    purchaseDate: "20-11-2022",
    lastMaintenance: "25-03-2023",
    nextMaintenance: "25-06-2023",
    location: "Building A, Floor 1, Section 6",
    assignedStation: "Unassigned",
    notes: "Backup AOI system for contingency operations.",
  },
  {
    id: "eq-backup-reflow-313",
    name: "Backup Reflow Oven",
    status: "maintenance",
    type: "Thermal Equipment",
    serialNumber: "RFO-4321-2022",
    model: "ThermalFlow Standard",
    manufacturer: "ThermalTech",
    purchaseDate: "15-10-2022",
    lastMaintenance: "10-02-2023",
    nextMaintenance: "10-05-2023",
    location: "Building A, Floor 2, Section 6",
    assignedStation: "Unassigned",
    notes: "Backup reflow oven for maintenance periods and overflow production.",
  },
  {
    id: "eq-portable-rework-414",
    name: "Portable Rework Station",
    status: "operational",
    type: "Rework Equipment",
    serialNumber: "RWS-6543-2023",
    model: "ReworkPro Portable",
    manufacturer: "RepairTech",
    purchaseDate: "05-01-2023",
    lastMaintenance: "12-03-2023",
    nextMaintenance: "12-06-2023",
    location: "Building B, Floor 2, Section 5",
    assignedStation: "Unassigned",
    notes: "Portable rework station for on-site repairs and adjustments.",
  },
  {
    id: "eq-calibration-tools-515",
    name: "Calibration Tool Set",
    status: "operational",
    type: "Testing Equipment",
    serialNumber: "CTS-9876-2023",
    model: "CalMaster Pro",
    manufacturer: "PrecisionTools",
    purchaseDate: "20-02-2023",
    lastMaintenance: "15-04-2023",
    nextMaintenance: "15-07-2023",
    location: "Building C, Floor 1, Section 5",
    assignedStation: "Unassigned",
    notes: "Comprehensive calibration tool set for equipment maintenance and verification.",
  },
  {
    id: "eq-component-counter-616",
    name: "Component Counter",
    status: "operational",
    type: "SMT Equipment",
    serialNumber: "CCT-5432-2023",
    model: "CountMaster 3000",
    manufacturer: "SMTech",
    purchaseDate: "10-03-2023",
    lastMaintenance: "20-04-2023",
    nextMaintenance: "20-07-2023",
    location: "Building A, Floor 1, Section 4",
    assignedStation: "Unassigned",
    notes: "Automated component counting system for inventory management.",
  },
]










export const STATION_TYPES = [
  "Laser Etching",
  "Screen Printing",
  "Pick & Place",
  "Hand Placement",
  "Reflow",
  "AOI",
  "Visual Inspection",
  "Touch Up",
  "PTH",
  "X-Ray",
  "Wave Solder",
  "Wash Clean",
  "Chemical Wash",
]

export const STATION_STATUSES = ["Active", "Maintenance", "Inactive"]

export const STATION_TYPE_ICONS: Record<string, string> = {
  aoi: "eye",
  "pick & place": "cpu",
  "chemical wash": "droplet",
  "wash clean": "droplet",
  "hand placement": "hand-metal",
  pth: "hand-metal",
  "wave solder": "zap",
  "screen printing": "printer",
  reflow: "rotate-cw",
  "touch up": "pen-tool",
  "x-ray": "layers",
  "visual inspection": "eye",
  "laser etching": "zap",
}

// Define STORAGE_KEYS locally since it's not exported from constants
// const STORAGE_KEYS = {
//   STATIONS: "meritronics-stations",
//   EQUIPMENT: "meritronics-equipment",
//   SETTINGS: "meritronics-settings",
//   USER_PREFERENCES: "meritronics-user-preferences",
// }

// Mock Stations Data
export const MOCK_STATIONS = [
  {
    id: "sta-aoi-station-1-123",
    name: "AOI Station 1",
    description: "Automated Optical Inspection station for PCB quality control",
    type: "AOI",
    code: "STA-AOI001",
    status: "active",
    location: "Building A, Floor 1, Section 3",
    operator: "John Smith",
    lastMaintenance: "15-03-2023",
    nextMaintenance: "15-06-2023",
    efficiency: 92,
    equipment: [
      {
        id: "eq-aoi-system-456",
        name: "Automated Optical Inspection System",
        status: "operational",
        type: "Inspection Equipment",
        serialNumber: "AOI-2345-2023",
      },
    ],
    createdAt: "2022-06-15T10:00:00Z",
    updatedAt: "2023-04-10T14:30:00Z",
  },
  {
    id: "sta-chemical-wash-234",
    name: "Chemical Wash Station",
    description: "Chemical washing and cleaning of PCBs",
    type: "Chemical Wash",
    code: "STA-CHE012",
    status: "maintenance",
    location: "Building A, Floor 1, Section 5",
    operator: "Jane Doe",
    lastMaintenance: "10-02-2023",
    nextMaintenance: "10-05-2023",
    efficiency: 85,
    equipment: [
      {
        id: "eq-chemical-wash-789",
        name: "Chemical Wash System",
        status: "maintenance",
        type: "Cleaning Equipment",
        serialNumber: "CWS-1234-2022",
      },
    ],
    createdAt: "2022-05-20T09:00:00Z",
    updatedAt: "2023-03-15T11:45:00Z",
  },
  {
    id: "sta-hand-placement-345",
    name: "Hand Placement Station 1",
    description: "Manual component placement station",
    type: "Hand Placement",
    code: "STA-HAN023",
    status: "active",
    location: "Building B, Floor 2, Section 1",
    operator: "Robert Johnson",
    lastMaintenance: "20-04-2023",
    nextMaintenance: "20-07-2023",
    efficiency: 88,
    equipment: [
      {
        id: "eq-component-placement-101",
        name: "Component Placement System",
        status: "operational",
        type: "Assembly Equipment",
        serialNumber: "CPS-5678-2023",
      },
    ],
    createdAt: "2022-07-10T08:30:00Z",
    updatedAt: "2023-04-25T16:20:00Z",
  },
  {
    id: "sta-laser-etching-456",
    name: "Laser Etching Station 1",
    description: "Laser etching and marking station",
    type: "Laser Etching",
    code: "STA-LAS034",
    status: "active",
    location: "Building B, Floor 2, Section 3",
    operator: "Lisa Park",
    lastMaintenance: "05-03-2023",
    nextMaintenance: "05-06-2023",
    efficiency: 95,
    equipment: [
      {
        id: "eq-laser-etching-202",
        name: "Laser Etching System",
        status: "operational",
        type: "Marking Equipment",
        serialNumber: "LES-9012-2022",
      },
    ],
    createdAt: "2022-08-05T13:15:00Z",
    updatedAt: "2023-03-10T09:50:00Z",
  },
  {
    id: "sta-pick-place-567",
    name: "Pick and Place Station 1",
    description: "Automated component placement station",
    type: "Pick & Place",
    code: "STA-PIC045",
    status: "active",
    location: "Building A, Floor 2, Section 2",
    operator: "Michael Chen",
    lastMaintenance: "12-04-2023",
    nextMaintenance: "12-07-2023",
    efficiency: 93,
    equipment: [
      {
        id: "eq-pick-place-303",
        name: "Pick and Place Machine",
        status: "operational",
        type: "SMT Equipment",
        serialNumber: "PPM-3456-2023",
      },
    ],
    createdAt: "2022-09-12T11:30:00Z",
    updatedAt: "2023-04-15T14:10:00Z",
  },
  {
    id: "sta-pth-678",
    name: "PTH Manual Load Station",
    description: "Through-hole component loading station",
    type: "PTH",
    code: "STA-PTH056",
    status: "inactive",
    location: "Building C, Floor 1, Section 1",
    operator: "Sarah Williams",
    lastMaintenance: "25-02-2023",
    nextMaintenance: "25-05-2023",
    efficiency: 80,
    equipment: [
      {
        id: "eq-pth-insertion-404",
        name: "Through-hole Insertion System",
        status: "offline",
        type: "Assembly Equipment",
        serialNumber: "TIS-7890-2022",
      },
    ],
    createdAt: "2022-10-08T10:45:00Z",
    updatedAt: "2023-03-01T15:30:00Z",
  },
  {
    id: "sta-reflow-789",
    name: "Reflow Oven Station",
    description: "Reflow soldering oven for SMT assembly",
    type: "Reflow",
    code: "STA-REF067",
    status: "active",
    location: "Building A, Floor 2, Section 4",
    operator: "David Miller",
    lastMaintenance: "18-03-2023",
    nextMaintenance: "18-06-2023",
    efficiency: 90,
    equipment: [
      {
        id: "eq-reflow-oven-505",
        name: "Reflow Oven",
        status: "operational",
        type: "Thermal Equipment",
        serialNumber: "RFO-2345-2022",
      },
    ],
    createdAt: "2022-11-15T09:20:00Z",
    updatedAt: "2023-03-22T13:40:00Z",
  },
  {
    id: "sta-screen-printing-890",
    name: "Screen Printing Station 1",
    description: "Solder paste screen printing station",
    type: "Screen Printing",
    code: "STA-SCR078",
    status: "active",
    location: "Building B, Floor 1, Section 2",
    operator: "Emma Davis",
    lastMaintenance: "02-04-2023",
    nextMaintenance: "02-07-2023",
    efficiency: 87,
    equipment: [
      {
        id: "eq-screen-printer-606",
        name: "Screen Printer",
        status: "operational",
        type: "Printing Equipment",
        serialNumber: "SPR-6789-2023",
      },
    ],
    createdAt: "2022-12-10T14:00:00Z",
    updatedAt: "2023-04-05T10:15:00Z",
  },
  {
    id: "sta-touch-up-901",
    name: "Touch Up Station 1",
    description: "Manual touch-up and rework station",
    type: "Touch Up",
    code: "STA-TOU089",
    status: "active",
    location: "Building C, Floor 1, Section 3",
    operator: "James Wilson",
    lastMaintenance: "08-03-2023",
    nextMaintenance: "08-06-2023",
    efficiency: 85,
    equipment: [
      {
        id: "eq-rework-station-707",
        name: "Rework Station",
        status: "operational",
        type: "Rework Equipment",
        serialNumber: "RWS-1234-2022",
      },
    ],
    createdAt: "2023-01-05T11:30:00Z",
    updatedAt: "2023-03-12T16:45:00Z",
  },
  {
    id: "sta-visual-inspection-012",
    name: "Visual Inspection Station 1",
    description: "Manual visual inspection station",
    type: "Visual Inspection",
    code: "STA-VIS090",
    status: "active",
    location: "Building A, Floor 1, Section 1",
    operator: "Maria Garcia",
    lastMaintenance: "15-04-2023",
    nextMaintenance: "15-07-2023",
    efficiency: 92,
    equipment: [
      {
        id: "eq-inspection-system-808",
        name: "Inspection System",
        status: "operational",
        type: "Quality Control Equipment",
        serialNumber: "INS-5678-2023",
      },
    ],
    createdAt: "2023-02-12T10:00:00Z",
    updatedAt: "2023-04-20T13:20:00Z",
  },
  {
    id: "sta-wash-clean-123",
    name: "Wash Clean Station",
    description: "PCB washing and cleaning station",
    type: "Wash Clean",
    code: "STA-WAS101",
    status: "maintenance",
    location: "Building B, Floor 1, Section 4",
    operator: "Thomas Anderson",
    lastMaintenance: "20-02-2023",
    nextMaintenance: "20-05-2023",
    efficiency: 83,
    equipment: [
      {
        id: "eq-pcb-washing-909",
        name: "PCB Washing System",
        status: "maintenance",
        type: "Cleaning Equipment",
        serialNumber: "PWS-9012-2022",
      },
    ],
    createdAt: "2023-01-25T09:45:00Z",
    updatedAt: "2023-03-05T11:10:00Z",
  },
  {
    id: "sta-wave-solder-234",
    name: "Wave Soldering Station",
    description: "Wave soldering for through-hole components",
    type: "Wave Solder",
    code: "STA-WAV112",
    status: "active",
    location: "Building C, Floor 2, Section 2",
    operator: "Olivia Martin",
    lastMaintenance: "10-03-2023",
    nextMaintenance: "10-06-2023",
    efficiency: 89,
    equipment: [
      {
        id: "eq-wave-solder-010",
        name: "Wave Soldering Machine",
        status: "operational",
        type: "Soldering Equipment",
        serialNumber: "WSM-3456-2022",
      },
    ],
    createdAt: "2023-02-08T13:30:00Z",
    updatedAt: "2023-03-15T15:50:00Z",
  },
  {
    id: "sta-xray-345",
    name: "X-Ray Inspection Station",
    description: "X-ray inspection for hidden solder joints",
    type: "X-Ray",
    code: "STA-XRA123",
    status: "active",
    location: "Building A, Floor 2, Section 5",
    operator: "William Brown",
    lastMaintenance: "05-04-2023",
    nextMaintenance: "05-07-2023",
    efficiency: 94,
    equipment: [
      {
        id: "eq-xray-system-111",
        name: "X-Ray Inspection System",
        status: "operational",
        type: "Inspection Equipment",
        serialNumber: "XRS-7890-2023",
      },
    ],
    createdAt: "2023-03-01T10:15:00Z",
    updatedAt: "2023-04-10T12:30:00Z",
  },
]
